services:
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:delegated
    working_dir: /var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      PHP_IDE_CONFIG: "serverName=find_it"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  web:
    image: nginx:alpine
    depends_on: [php]
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:delegated
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
